### PR TITLE
v3.0.0-rc.29

### PR DESCRIPTION
**Pull request by oleksandr-danylchenko**
Having the new version with the `Lifecycle` observers registering [fix](https://github.com/annotorious/annotorious/pull/409) will help to proceed with closing the https://github.com/recogito/text-annotator-js/issues/107

### CODE REVIEW

**Comment by oleksandr-danylchenko** [comment]
Could you please deploy this version? 🙏🏻🙏🏻🙏🏻
It blocks me from proceeding to work on my app. When I try to link all the transitive deps locally - Vite doesn't pick up the changes ;(

**Comment by oleksandr-danylchenko** [comment]
Please, it's the only thing dragging me down now 🙏🏻🙏🏻🙏🏻

**Comment by rsimon** [comment]
Published now!

**Comment by oleksandr-danylchenko** [comment]
Thank you!

**Pull request closed without merging**
